[package]
name = "ruff_annotate_snippets"
version = "0.0.3"
description = "This is an internal component crate of Ruff"
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = "MIT OR Apache-2.0"

[dependencies]
anstyle = { workspace = true }
memchr = { workspace = true, optional = true }
unicode-width = { workspace = true }

[dev-dependencies]
ruff_annotate_snippets = { path = ".", features = ["testing-colors"] }
anstream = { workspace = true }
snapbox = { workspace = true }

[features]
default = ["std"]
std = ["anstyle/std", "memchr?/std"]
simd = ["dep:memchr"]
testing-colors = []

[lints]
workspace = true

[lib]
name = "annotate_snippets"
test = false
